services:
  chat-server:
    build: .
    container_name: chat-distributed-server
    ports:
      - "1099:1099"  # RMI registry port
    environment:
      - JAVA_OPTS=-Djava.rmi.server.hostname=host.docker.internal -Djava.net.preferIPv4Stack=true -Djava.rmi.server.useLocalHostname=false
      - SERVER_PORT=1099
      - SERVER_NAME=ChatServer
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For Windows Docker Desktop
    networks:
      - chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -an | grep 1099"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  chat-network:
    driver: bridge
